package com.raed.twitterclient.timeline;

public enum  TLEvent {

    LOADING_NEW_TWEETS,
    FAIL_TO_LOAD_NEW_TWEETS,
    NEW_TWEETS_LOADED_SUCCESSFULLY,

    LOADING_OLD_TWEETS,
    FAIL_TO_LOAD_OLD_TWEETS,
    OLD_TWEETS_LOADED_SUCCESSFULLY

}
